# Generated by Django 6.0.5 on 2026-05-26 14:26

import myauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=myauth.models.avatar_directory_path
            ),
        ),
    ]
